on:
  workflow_dispatch:
  push:
    branches: [main]

name: Quarto Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # useful for Quarto sites that read git history

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Install R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.4.0'
          use-public-rspm: true  # faster binary installs on Linux

      - name: Install system dependencies (curl, SSL, XML)
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev

      - name: Install R Dependencies via renv
        uses: r-lib/actions/setup-renv@v2
        with:
          cache-version: 1

      # Optional: ensure curl package is present explicitly (if not in renv.lock)
      # - name: Ensure R package 'curl' is installed
      #   run: Rscript -e "if (!requireNamespace('curl', quietly=TRUE)) install.packages('curl', repos='https://cloud.r-project.org')"

      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}